### ISSUE TITLE
circular dependency (old mongo version)

### ISSUE THREAD

**Issue by davidchieregato** [jmdisuanco/pinipig#14]
Hello
I just started doing some experiments with pinipig.
When you run `npm run dev` with node 14 and try to access any mongo related path with the mongo driver actually present in the package.json ("mongodb": "^3.1.13") it will throw the following error and won't give any answer to the requests: 
`(node:7476) Warning: Accessing non-existent property 'count' of module exports inside circular dependency                                   (Use `node --trace-warnings ...` to show where the warning was created)                                                                     (node:7476) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency                                 (node:7476) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency                                  (node:7476) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency`
It will be solved by updating the dependency: https://www.mongodb.com/community/forums/t/warning-accessing-non-existent-property-count-of-module-exports-inside-circular-dependency/3183
when using "mongodb": "^3.5.7" it will work correctly.

**Comment by jmdisuanco** [comment]
Thank you for the PR David! 

Your changes is now available in version v1.7.6
